Pandas - Planilha - Data Frame

Resumão:

A biblioteca 'Pandas' possibilita diversas manipulações dentro de uma planilha (data frame).
A planilha de dados (csv) deve estar baixada no mesmo diretório (a esquerda) que o código está sendo utilizado.

Funções aprendidas:
1. dados.shape = saber as dimensões da tabela.
2. dados.describe = dados estatísticos dos números da tabela: média, máximo, mínimo, desvio padrão...
3. dados.head(n) = 'n' primeiras linhas da tabela.
4. dados.tail(n) = 'n' últimas linhas da tabela.
5. dados[['nome_coluna']] = filtra a tabela pela coluna.
6. dados.loc[[0:3]] = filta as primeiras quatro colunas. não precisa necessariamente ser um intervalo.
7. dados.iloc[a:b,x:y] = filtra da coluna 'a' até 'b' e da linha 'x' até 'y'.
8. dados.loc[dados['coluna'] == i] = filtra apenas os valores da coluna específica que atendem a condição "== i" (suporta < ou > também).
obs.: também é possível expandir essa forma para coletar dados de colunas específicas para linhas que atendem a condição pedida (ver minha_idade)
9. pd.Series = cria séries matemáticas de números ou strings e numera cada item. As séries podem ser criadas manualmente, com vetores (numpy) ou com o próprio data frame.
10. dados.rename = serve para renomear colunas.
11. dados.drop = serve para excluir colunas.
obs.: usar o comando inplace = true exclui/renomeia as colunas de forma permanente dali pra frente, ao invés de fazê-lo apenas para aquele bloco.

In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_csv("Credit.csv")

In [ ]:
# para saber o número de (linhas, colunas):

dados.shape

(1000, 21)

In [ ]:
# descrições estatísticas básicas dos dados NUMÉRICOS da planilha.

dados.describe()

# 1000 pessoas serão analisadas. Da tabela abaixo, tiramos conclusões , por exemplo,
# sobre as idades máximas, mínimas e média dos participantes analisados,
# a quantidade de dinheiro (crédito), o número de dependentes deles, etc.

,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000

In [ ]:
# as primeiras 5 linhas da planilha.

dados.head()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad

In [ ]:
# as últimas 5 linhas da planilha:

dados.tail()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
995,'no checking',12,'existing paid',furniture/equipment,1736,<100,4<=X<7,3,'female div/dep/mar',none,...,'real estate',31,none,own,1,'unskilled resident',1,none,yes,good
996,<0,30,'existing paid','used car',3857,<100,1<=X<4,4,'male div/sep',none,...,'life insurance',40,none,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
997,'no checking',12,'existing paid',radio/tv,804,<100,>=7,4,'male single',none,...,car,38,none,own,1,skilled,1,none,yes,good
998,<0,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,0<=X<200,45,'critical/other existing credit','used car',4576,100<=X<500,unemployed,3,'male single',none,...,car,27,none,own,1,skilled,1,none,yes,good

In [ ]:
# as primeiras/últimas linhas com parâmetros:

dados.head(3)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good

In [ ]:
dados[['age']]

# filtrando a planilha por coluna.

     age
0     67
1     22
2     49
3     45
4     53
..   ...
995   31
996   40
997   38
998   23
999   27

[1000 rows x 1 columns]

In [ ]:
dados.loc[600:602]

# filtrando linhas por intervalos

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
600,0<=X<200,7,'existing paid',radio/tv,2329,<100,<1,1,'female div/dep/mar',guarantor,...,'real estate',45,none,own,1,skilled,1,none,yes,good
601,0<=X<200,9,'existing paid',furniture/equipment,918,<100,1<=X<4,4,'female div/dep/mar',none,...,'life insurance',30,none,own,1,skilled,1,none,yes,bad
602,0<=X<200,24,'all paid',education,1837,<100,4<=X<7,4,'female div/dep/mar',none,...,'no known property',34,bank,'for free',1,'unskilled resident',1,none,yes,bad

In [ ]:
dados.loc[[272,871,937]]

#localizando colunas específicas.

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
272,0<=X<200,48,'all paid','new car',12169,'no known savings',unemployed,4,'male single','co applicant',...,'no known property',36,none,'for free',1,'high qualif/self emp/mgmt',1,yes,yes,good
871,>=200,6,'critical/other existing credit','new car',1343,<100,>=7,1,'male single',none,...,'real estate',46,none,own,2,skilled,2,none,no,good
937,0<=X<200,6,'existing paid',radio/tv,2063,<100,<1,4,'male mar/wid',none,...,car,30,none,rent,1,'high qualif/self emp/mgmt',1,yes,yes,good

In [ ]:
dados.loc[dados['age'] <= 19]

## filtrando apenas colunas que interessam. ('filtro' do excel).

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
391,0<=X<200,12,'existing paid',furniture/equipment,983,>=1000,<1,1,'female div/dep/mar',none,...,'real estate',19,none,rent,1,'unskilled resident',1,none,yes,good
633,'no checking',9,'existing paid',furniture/equipment,1980,<100,<1,2,'female div/dep/mar','co applicant',...,car,19,none,rent,2,skilled,1,none,yes,bad

In [ ]:
mlks = dados.loc[dados['age'] <= 19]

print(mlks)

# também é possível separar os resultados do filtros com uma variável.

    checking_status  duration   credit_history              purpose  \
391        0<=X<200        12  'existing paid'  furniture/equipment
633   'no checking'         9  'existing paid'  furniture/equipment

     credit_amount savings_status employment  installment_commitment  \
391            983         >=1000         <1                       1
633           1980           <100         <1                       2

          personal_status   other_parties  ...  property_magnitude age  \
391  'female div/dep/mar'            none  ...       'real estate'  19
633  'female div/dep/mar'  'co applicant'  ...                 car  19

     other_payment_plans housing existing_credits                   job  \
391                 none    rent                1  'unskilled resident'
633                 none    rent                2               skilled

    num_dependents  own_telephone foreign_worker class
391              1           none            yes  good
633              1           none            yes   bad

[2 rows x 21 columns]

In [ ]:
minha_idade = dados[['savings_status','num_dependents','own_telephone']].loc[dados['age'] == 23]
print(minha_idade)

# quero saber quanto dinheiro as pessoas de 23 anos tem, o número de dependentes
# e se possuem celular.

         savings_status  num_dependents own_telephone
47          500<=X<1000               1           yes
58                 <100               1          none
59                 <100               1           yes
111                <100               1           yes
118         500<=X<1000               1          none
144                <100               1           yes
217                <100               1           yes
221  'no known savings'               1           yes
236  'no known savings'               1           yes
258          100<=X<500               1           yes
280              >=1000               1           yes
334                <100               2          none
336                <100               1          none
346                <100               1          none
347         500<=X<1000               1          none
350                <100               1           yes
355                <100               1          none
359                <100               1          none
372                <100               1          none
417  'no known savings'               1           yes
436         500<=X<1000               1          none
471                <100               1          none
480                <100               1          none
517                <100               1           yes
523          100<=X<500               1          none
540                <100               1          none
550  'no known savings'               1          none
565          100<=X<500               1           yes
570                <100               1           yes
596                <100               1          none
604                <100               1          none
632  'no known savings'               1          none
660                <100               1          none
661  'no known savings'               1          none
736                <100               1          none
741                <100               1          none
746                <100               1          none
751                <100               1          none
752          100<=X<500               1          none
783          100<=X<500               1          none
831                <100               1           yes
837                <100               2          none
842                <100               1          none
887                <100               1           yes
934                <100               1          none
966         500<=X<1000               1          none
992  'no known savings'               1          none
998                <100               1           yes

In [ ]:
serie_pares = pd.Series([2,4,6,8,10,12,14,16])
print(serie_pares)

# Criando uma série. O output tem a numeração de cada item, a0, a1, a2...

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
dtype: int64

In [ ]:
serie_impares = s1 - 1
print(serie_impares)

0     1
1     3
2     5
3     7
4     9
5    11
6    13
7    15
dtype: int64

In [ ]:
import numpy as np

vetor1 = np.array([10,20,30,40])
s1 = pd.Series(vetor1)

print(s1)

# criando uma série a partir de um vetor.

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
s2 = dados['age']
print(s2)

# criando uma serie a partir de um data frame (planilha).

0      67
1      22
2      49
3      45
4      53
       ..
995    31
996    40
997    38
998    23
999    27
Name: age, Length: 1000, dtype: int64

In [ ]:
dados.rename(columns={'duration':'duração','age':'idade', 'purpose':'objetivo'}, inplace = True)

# renomeando colunas. O 'inplace = True' deixa a mudança permanente.

In [ ]:
dados.drop('other_payment_plans',axis=1,inplace=True)

# para excluir coluna. O 'inplace = True' deixa a mudança permanente.

In [ ]:
dados.head(1)

,duração,credit_history,objetivo,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,idade,housing,existing_credits,job,num_dependents,own_telephone,class
0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,4,'real estate',67,own,2,skilled,1,yes,good

In [ ]:
dados.isnull().sum()

# verificando se há dados nulos

duração                   0
credit_history            0
objetivo                  0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
idade                     0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
class                     0
dtype: int64

In [ ]:

dados.iloc[0:3,0:5]

# localização específica de linhas e colunas por intervalos.

,duração,credit_history,objetivo,credit_amount,savings_status
0,6,'critical/other existing credit',radio/tv,1169,'no known savings'
1,48,'existing paid',radio/tv,5951,<100
2,12,'critical/other existing credit',education,2096,<100

In [ ]:
dados.iloc[[5,10,15,20,25,30],0:6]

# iloc sem intervalos.

,duração,credit_history,objetivo,credit_amount,savings_status,employment
5,36,'existing paid',education,9055,'no known savings',1<=X<4
10,12,'existing paid','new car',1295,<100,<1
15,24,'existing paid',radio/tv,1282,100<=X<500,1<=X<4
20,9,'critical/other existing credit','new car',2134,<100,1<=X<4
25,6,'existing paid',furniture/equipment,1374,<100,1<=X<4
30,18,'existing paid',business,1913,>=1000,<1